### ISSUE TITLE
The generated README from v1 template contains a little error

### ISSUE THREAD

**Issue by mlenormand** [rstoenescu/quasar-templates#1]
The README generated from the v1 template indicates the 'quasar play' command to serve with hot reload, instead of the 'quasar dev' command

**Comment by rstoenescu** [comment]
Would you be so kind to make a PR? It takes a minute at most. Just hit the "edit" icon on the README file and edit it in place. Thank you!

**Comment by rstoenescu** [comment]
Fixed. Thanks for reporting this!
